<?php
/**
 * @file
 * hwc_good_practice_exchange.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function hwc_good_practice_exchange_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function hwc_good_practice_exchange_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_fe_nodequeue_export_fields().
 */
function hwc_good_practice_exchange_fe_nodequeue_export_fields() {
  $nodequeues = array();

  // Exported nodequeues: good_practice_exchange_intro
  $nodequeues['good_practice_exchange_intro'] = array(
    'name' => 'good_practice_exchange_intro',
    'title' => 'Good practice exchange intro',
    'subqueue_title' => '',
    'size' => 0,
    'link' => '',
    'link_remove' => '',
    'owner' => 'nodequeue',
    'show_in_ui' => 1,
    'show_in_tab' => 1,
    'show_in_links' => 0,
    'reference' => 0,
    'reverse' => 0,
    'i18n' => 0,
    'subqueues' => 1,
    'types' => array(
      0 => 'article',
    ),
    'roles' => array(),
    'count' => 0,
  );

  return $nodequeues;
}

/**
 * Implements hook_node_info().
 */
function hwc_good_practice_exchange_node_info() {
  $items = array(
    'document' => array(
      'name' => 'Document',
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => 'Title',
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
