<?php
/**
 * @file
 * hwc_practical_tool.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function hwc_practical_tool_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-11ABW7bHR7jxlsi7kP1x0I81mePGjicE'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '11ABW7bHR7jxlsi7kP1x0I81mePGjicE',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'practical-tools
tools-and-publications/practical-tools',
    'roles' => array(),
    'themes' => array(
      'hwc_frontend' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'hwc_frontend',
        'weight' => -79,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Item language',
    'visibility' => 1,
  );

  $export['facetapi-3wdzGmfuaWV8dFrp0unV5StIH22e8cRK'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '3wdzGmfuaWV8dFrp0unV5StIH22e8cRK',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'hwc_frontend' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'hwc_frontend',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-6V9dPHi6gLvKkQis1yAzmf7URMn2z2xN'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '6V9dPHi6gLvKkQis1yAzmf7URMn2z2xN',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'practical-tools
tools-and-publications/practical-tools',
    'roles' => array(),
    'themes' => array(
      'hwc_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'hwc_frontend',
        'weight' => -81,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Worker groups:',
    'visibility' => 1,
  );

  $export['facetapi-CMdKaPNpQUELSbMFeop7CrP1w6I0EvuU'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'CMdKaPNpQUELSbMFeop7CrP1w6I0EvuU',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'practical-tools
tools-and-publications/practical-tools',
    'roles' => array(),
    'themes' => array(
      'hwc_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'hwc_frontend',
        'weight' => -87,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Country:',
    'visibility' => 1,
  );

  $export['facetapi-H521BlbvKT4VvBQ0eUjaRB22CnF0x2vm'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'H521BlbvKT4VvBQ0eUjaRB22CnF0x2vm',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'hwc_frontend' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'hwc_frontend',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-WIDhFWDUEw0jl3l0E37RscD1I4NQZp9y'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'WIDhFWDUEw0jl3l0E37RscD1I4NQZp9y',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'hwc_frontend' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'hwc_frontend',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-arApaxtlviAahyIYl4eWPMPSYulwF5hS'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'arApaxtlviAahyIYl4eWPMPSYulwF5hS',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'practical-tools
tools-and-publications/practical-tools',
    'roles' => array(),
    'themes' => array(
      'hwc_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'hwc_frontend',
        'weight' => -82,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Health effects:',
    'visibility' => 1,
  );

  $export['facetapi-dn0ROYIfxwx0uGZSLR6ujE2pFn6Rg3vp'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'dn0ROYIfxwx0uGZSLR6ujE2pFn6Rg3vp',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'practical-tools
tools-and-publications/practical-tools',
    'roles' => array(),
    'themes' => array(
      'hwc_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'hwc_frontend',
        'weight' => -83,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Work tasks:',
    'visibility' => 1,
  );

  $export['facetapi-gHIFBfP3YHFOxiAV4q6IJVpi1KM0eVj6'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'gHIFBfP3YHFOxiAV4q6IJVpi1KM0eVj6',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'practical-tools
tools-and-publications/practical-tools',
    'roles' => array(),
    'themes' => array(
      'hwc_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'hwc_frontend',
        'weight' => -84,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Sector / Industry:',
    'visibility' => 1,
  );

  $export['facetapi-qKTjjfj4pcxhK1CKxcJbuoCqljfnWqbE'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'qKTjjfj4pcxhK1CKxcJbuoCqljfnWqbE',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'practical-tools
tools-and-publications/practical-tools
partners-documents',
    'roles' => array(),
    'themes' => array(
      'hwc_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'hwc_frontend',
        'weight' => -85,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Language:',
    'visibility' => 1,
  );

  $export['facetapi-r1CPZ0bxJkiGazQqrYQUlYoa5mMbO8qj'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'r1CPZ0bxJkiGazQqrYQUlYoa5mMbO8qj',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'practical-tools
tools-and-publications/practical-tools',
    'roles' => array(),
    'themes' => array(
      'hwc_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'hwc_frontend',
        'weight' => -80,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Target groups:',
    'visibility' => 1,
  );

  $export['facetapi-wQIFZjkOyQ5XU931SF9uzdto5FrPfZQI'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'wQIFZjkOyQ5XU931SF9uzdto5FrPfZQI',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'practical-tools
tools-and-publications/practical-tools',
    'roles' => array(),
    'themes' => array(
      'hwc_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'hwc_frontend',
        'weight' => -88,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Type:',
    'visibility' => 1,
  );

  $export['hwc_practical_tool-hwc_practical_tool_language_list'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'hwc_practical_tool_language_list',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'hwc_practical_tool',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'hwc_frontend' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'hwc_frontend',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['hwc_practical_tool-hwc_practical_tool_text'] = array(
    'cache' => 8,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'hwc_practical_tool_text',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'hwc_practical_tool',
    'node_types' => array(),
    'pages' => 'practical-tools
tools-and-publications/practical-tools',
    'roles' => array(),
    'themes' => array(
      'hwc_frontend' => array(
        'region' => 'below_title',
        'status' => 1,
        'theme' => 'hwc_frontend',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['views--exp-practical_tools-page'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '-exp-practical_tools-page',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'practical-tools
tools-and-publications/practical-tools',
    'roles' => array(),
    'themes' => array(
      'hwc_frontend' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'hwc_frontend',
        'weight' => -93,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  return $export;
}
