<?php
/**
 * @file
 * Code for the OSHA Audio Visual feature.
 */

include_once 'hwc_audio_visual.features.inc';

/**
 * Implements hook_init.
 */
function hwc_audio_visual_init() {
  $item = menu_get_object();
  if (
    (implode('_', arg()) == 'node_add_audio-visual') ||
    ($item && $item->type == 'practical_tool')
  ) {
    drupal_add_css(drupal_get_path('module', 'hwc_audio_visual') .'/css/hwc_audio_visual.css');
  }
}

function hwc_audio_visual_preprocess_views_view(&$vars) {
  $view = $vars['view'];
  if ($view->name == 'practical_tool') {
    drupal_add_css(drupal_get_path('module', 'hwc_audio_visual') .'/css/hwc_audio_visual.css');
  }
}

/**
 * Implements hook_element_info_alter.
 */
function hwc_audio_visual_element_info_alter(&$type) {
  if (isset($type['text_format']['#process'])) {
    foreach ($type['text_format']['#process'] as &$callback) {
      if ($callback === 'filter_process_format') {
        $callback = 'hwc_audio_visual_filter_process_format';
      }
    }
  }
}

// Remove guidelines and help text.
function hwc_audio_visual_filter_process_format($element) {
  $element = filter_process_format($element);
  if ((isset($element['#bundle'])) && ($element['#bundle'] == 'practical_tool')) {
    unset($element['format']['guidelines']);
    unset($element['format']['help']);
    $element['format']['format']['#options'] = ['audio_visual' => $element['format']['format']['#options']['audio_visual']];
    unset($element['format']['format']['']);
    $element['#format'] = 'audio_visual';
  }
  return $element;
}
